require('plugins')
require('keymaps')
require('settings')
require('colorscheme')

require('compe-config')
require('autopairs-config')
require('galaxyline-config')
require('bufferline-config')
require('colorizer-config')
require('nvim-comment-config')
require('tree-sitter-config')
require('neogit-config')
require('gitsigns-config')
require('closetag-config')
require('dial-config')
require('dashboard-config')

vim.cmd('source $HOME/.config/nvim/vimscript/which-key-config.vim')

require('lsp')
require('lsp.lua-ls')
require('lsp.js-ts-ls')
require('lsp.python-ls')
require('lsp.bash-ls')
require('lsp.css-ls')
require('lsp.html-ls')
require('lsp.json-ls')
require('lsp.vim-ls')
require('lsp.yaml-ls')
require('lsp.efm-general-ls')
