vim.cmd('set iskeyword+=-')
vim.cmd('set shortmess+=c')
vim.o.hidden=true
vim.wo.wrap=false
vim.cmd('set whichwrap+=<,>,[,],h,l')
vim.o.pumheight=10
vim.o.fileencoding="utf-8"
vim.o.cmdheight=2
vim.o.mouse="a"
vim.o.splitbelow=true
vim.o.termguicolors=true
vim.o.splitright=true
vim.o.t_Co="256"
vim.o.conceallevel=0
vim.cmd('set tabstop=2')
vim.cmd('set shiftwidth=2')
vim.cmd('set expandtab')
vim.cmd('set smartindent')
vim.wo.number = true
vim.wo.cursorline=true
vim.o.showtabline=2
vim.o.showmode=false
vim.o.backup=false
vim.o.writebackup=false
vim.wo.signcolumn="yes"
vim.o.updatetime=300
vim.o.timeoutlen=100
vim.o.clipboard="unnamedplus"
vim.o.hlsearch=false
vim.o.ignorecase=true
vim.wo.relativenumber=true
